# Image Node officielle
FROM node:20

# Dossier de travail
WORKDIR /app

# Copie des fichiers
COPY package*.json ./
RUN npm install --omit=dev
COPY . .

# Port exposé
EXPOSE 3000

# Lancement du serveur
CMD ["node", "server.js"]
