name: Test de l'action artefact-téléchargement

on:
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout du dépôt
        uses: actions/checkout@v3

      - name: 🧪 Utiliser l’action personnalisée
        uses: ./actions/artefact-téléchargement
        with:
          name: mon-artifact
          path: ./artifacts
